# Generated by Django 3.1 on 2020-12-23 10:25

import django.core.validators
from django.db import migrations, models
import forceartsapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('forceartsapi', '0002_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=models.ImageField(null=True, upload_to=forceartsapi.models.make_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])]),
        ),
    ]
