# Generated by Django 3.1 on 2020-12-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forceartsapi', '0003_auto_20201223_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
