# Generated by Django 3.1 on 2020-12-28 10:22

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('forceartsapi', '0004_wallpaper_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
