# Generated by Django 3.1 on 2021-01-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forceartsapi', '0005_wallpaper_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='characters'),
        ),
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
