# Generated by Django 3.1 on 2021-01-06 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forceartsapi', '0006_auto_20210106_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rank',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
