# Generated by Django 3.1 on 2021-01-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forceartsapi', '0007_auto_20210106_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default=None, max_length=255)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('message', models.TextField(blank=True, default=None)),
            ],
            options={
                'verbose_name': 'Contact-Us',
                'verbose_name_plural': 'Contact-Us',
            },
        ),
    ]
