# Generated by Django 3.1 on 2021-03-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forceartsapi', '0009_auto_20210320_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
