# Generated by Django 3.1 on 2021-04-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forceartsapi', '0010_wallpaper_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='views',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
