# Generated by Django 3.1 on 2021-06-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forceartsapi', '0011_wallpaper_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='visibility',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
