# Generated by Django 3.1 on 2021-08-27 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forceartsapi', '0012_wallpaper_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rank',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
