# Generated by Django 3.1 on 2021-11-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forceartsapi', '0013_auto_20210827_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='likes',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
